### ISSUE TITLE
请教个问题?接口Interactor是不是有些多余了?

### ISSUE THREAD

**Issue by xiaokanghell** [smuyyh/SprintNBA#12]
Interactor文件夹里,直接定义一个类并且定义对应的方法不就可以了,干嘛非要再实现Interactor接口呢?本人刚开始了解mvp模式,属于菜鸟一个,还请大神指点一下!

**Comment by smuyyh** [comment]
是。这很早以前写的了  没写好~    mvp规范实际上就是会存在大量的接口，所以大项目慎重。
