### ISSUE TITLE
虎扑是不是有些签名不一样啊 比如获取内容的api 和评论的api不一样

### ISSUE THREAD

**Issue by generalbao** [smuyyh/SprintNBA#22]
http://bbs.mobileapi.hupu.com/1/7.0.8/forums/getForumsInfoList?sign=f7ee5dce89def901984df373b38121d2&password=0&stamp=&token=&client=864454036694028&fid=44&night=0&lastTid=19393519&isHome=1&type=1&special=0&limit=20

/**
     * 虎扑url sign生成
     *
     * @param map url参数，按字典序拼接key和value
     * @return sign值
     */
    public static String getRequestSign(Map<String, String> map) {
        ArrayList<Map.Entry<String, String>> list = new ArrayList<>(map.entrySet());
        Collections.sort(list, new Comparator<Map.Entry<String, String>>() { // 字典序
            @Override
            public int compare(Map.Entry<String, String> lhs, Map.Entry<String, String> rhs) {
                return lhs.getKey().compareTo(rhs.getKey());
            }
        });
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < list.size(); i = i + 1) {
            if (builder.length() > 0) {
                builder.append("&");
            }
            Map.Entry<String, String> map1 = list.get(i);
            builder.append(map1.getKey()).append("=").append(map1.getValue());
        }
        builder.append("HUPU_SALT_AKJfoiwer394Jeiow4u309");
        return MD5.getMD5(builder.toString());
    }

这个签名是可以的 但是我评论的api不可以（通过抓包 ）
请教一下是不是不一样的签名

**Comment by smuyyh** [comment]
可能是吧，过去太久了，不大记得了
