### ISSUE TITLE
CommonLibrary那个库是自己写的么？

### ISSUE THREAD

**Issue by LeeQiWei** [smuyyh/SprintNBA#3]
RT~~~~

**Comment by smuyyh** [comment]
这只是手机常用的一些工具类、自定义控件等~~ 平时项目用到直接拿了

**Comment by LeeQiWei** [comment]
啊，这样呀，了解了，你也是虎扑JRS？

**Comment by LeeQiWei** [comment]
啊，这样呀，了解了，谢谢！
我现在是小白一枚，还不太知道怎么能不用开放API写出项目，写项目的时候也感到无从下手，方便加一下练习方式讨教么？

**Comment by smuyyh** [comment]
这不是开放API。虎扑平时也就看看帖子和新闻~没怎么玩。

**Comment by LeeQiWei** [comment]
谢谢啦，十分感谢，哈哈
