### ISSUE TITLE
你好，麻烦能告诉一下每一个球队的队标的网址是怎么找到的么？

### ISSUE THREAD

**Issue by LeeQiWei** [smuyyh/SprintNBA#6]
就是每一个球队的队标的网址，我根据你的地址能看到图片的，但是自己在腾讯NBA界面那个球队的信息里面并没有发现球队队标的独立网址。。。

**Comment by smuyyh** [comment]
腾讯的。你可以根据url+球队id 找到。这个基本是不变的

**Comment by LeeQiWei** [comment]
我要是想找到别的联赛的球队队标怎么能找到。。。。这个你知道么，先谢谢了

**Comment by smuyyh** [comment]
1. 比如西甲，找相关赛事类apk，解压，如果是本地资源res可以找到
2. 如果不是本地资源，那就抓包
3. 一般体育网站上球队资料里面也会有

**Comment by LeeQiWei** [comment]
谢谢耐心解答，非常感谢~~~~~~

**Comment by smuyyh** [comment]
客气哈~
