### ISSUE TITLE
运行时编译报错

### ISSUE THREAD

**Issue by zhoujingheng** [smuyyh/SprintNBA#7]
Error:(51, 65) 错误: 无法将类 DefaultCacheKeyFactory中的方法 getEncodedCacheKey应用到给定类型;
需要: ImageRequest,Object
找到: ImageRequest
原因: 实际参数列表和形式参数列表长度不同

**Comment by smuyyh** [comment]
Fresco的版本改了？

**Comment by zhoujingheng** [comment]
改了，不改好像编译不了。

**Comment by smuyyh** [comment]
怎么会编译不了... 什么错~

**Comment by zhoujingheng** [comment]
编译20多分钟，还在编译。。。

**Comment by smuyyh** [comment]
那你就看对应版本 getEncodedCacheKey 需要什么参数，改一下传给他。

**Comment by zhoujingheng** [comment]
public abstract CacheKey getEncodedCacheKey (ImageRequest request, Object callerContext)

Parameters
callerContext 	included for optional debugging or logging purposes only
Returns

    CacheKey for doing encoded image lookups in the pipeline.

**Comment by smuyyh** [comment]
看起来callercontext 没太大作用，可能用于统计和日志记录。看能不能new一个或者传null~ 新版本的我也没研究过
