### ISSUE TITLE
下载的apk版本里很多的视频播放不了啊？

### ISSUE THREAD

**Issue by AndroidNoobbbbbbbb** [smuyyh/SprintNBA#8]
您好，我发现像视频集锦，最佳进球界面里很多视频都播放不了，您最近有看过是什么情况吗

**Comment by smuyyh** [comment]
挺久没看了。播放不了是腾讯视频真实地址解析的问题

**Comment by AndroidNoobbbbbbbb** [comment]
好的，谢谢您的回答。
我也是试了下，按您源码里的{url}+{fn}?vkey这种方式去解析真实URL，
发现基本上访问的结果都是403，不知道是不是api加限制了。

**Comment by smuyyh** [comment]
之前大部分都是可以的。估计腾讯那边又更新了  有时间再去研究研究看

**Comment by smuyyh** [comment]
最近又研究了一下，还是不行。目测是加限制了…  暂时就只能跳转内嵌网页播放了
